# OSMnx
OSMNX_CACHE = True
OSMNX_LOG = True
NETWORK_TYPE = 'walk'

# Google Elevation API
GOOGLE_ELEVATION_API_KEY = ""
GOOGLE_ELEVATION_PAUSE = 0.05

# NBR9050
SEGMENT_LENGTH = 30.0       
MAX_GRADE_NBR9050 = 0.0833

# Visualização
DEFAULT_NODE_SIZE = 0
DEFAULT_EDGE_COLOR = '#800080'
DEFAULT_EDGE_WIDTH = 0.5
BACKGROUND_COLOR = 'white'

NUM_SIMULATIONS = 100
PERCOLATION_STEPS = 50

PLACES = {
    'botafogo': ["Botafogo, Rio de Janeiro, Brazil"],
}